Update messages.php
xingyicc/SocialNetworkingApp pull request #3
Opened 2023-03-21 06:17 UTC by sunithamundrathi

Hey Xingyi 

can you review the code and let me know the necessary changes?

2023-03-22 03:01 UTC, xingyicc commented on messages.php
> +$conn = new mysqli($servername, $username, $password, $dbname);
No need to connect to the database here. We do database connection in header.php. You should require header.php in this page.

2023-03-22 03:07 UTC, xingyicc requested changes

2023-03-22 03:07 UTC, xingyicc commented on messages.php
> +}
No need to connect to the database here. We do database connection in header.php. You should require header.php in this page.

2023-03-22 03:07 UTC, xingyicc commented on messages.php
We expected at least 2 functions: add/view. What I'm getting is an empty page. After refreshing, it shows no message. 
You can check the example page: https://github.com/RobinNixon/lpmj6/blob/master/robinsnest/messages.php

2023-03-24 04:56 UTC, sunithamundrathi commented
hi Xingyi

Can you review the updated changes and let me know if anything is needed?

thanks 
Sunitha Mundrathi

2023-03-24 06:26 UTC, merged